### ISSUE TITLE
toc问题

### ISSUE THREAD

**Issue by facm1999** [ddiu8081/ghost-theme-Moegi#11]
您好，请问我是用您添加toc.hbs后的版本为什么还是不能显示？
- 已使用codeinjection
- console中没有错误
- 网页源码中并无toc

**Comment by ddiu8081** [comment]
Hi，可以贴一下出现问题的地址么？
我这里还没排查出来

**Comment by facm1999** [comment]
> Hi，可以贴一下出现问题的地址么？
> 我这里还没排查出来

http://anfacm.com
十分感谢

**Comment by ddiu8081** [comment]
@facm1999 根据本主题引用的插件 [jquery.tocify.js](https://github.com/gfranko/jquery.tocify.js) 的设定，只有当存在最高级别标题时（在Moegi中是h2）才会显示目录。
目前你可以在文章中使用h2作为小标题。我也会在随后修复对其他级别标题的支持。
参考 https://github.com/gfranko/jquery.tocify.js/issues/65

**Comment by facm1999** [comment]
> @facm1999 根据本主题引用的插件 [jquery.tocify.js](https://github.com/gfranko/jquery.tocify.js) 的设定，只有当存在最高级别标题时（在Moegi中是h2）才会显示目录。
> 目前你可以在文章中使用h2作为小标题。我也会在随后修复对其他级别标题的支持。
> 参考 [gfranko/jquery.tocify.js#65](https://github.com/gfranko/jquery.tocify.js/issues/65)

好的，我明白了，谢谢您。
