### ISSUE TITLE
使用该主题样式并没有和作者您的博客样式一样呢

### ISSUE THREAD

**Issue by hiddletian** [ddiu8081/ghost-theme-Moegi#12]
添加您的主题后，需要重新编译嘛？我新建了一遍文章发现并没有加上上面那些归档的标签栏

**Comment by ddiu8081** [comment]
归档页、标签页等功能需要手动在ghost后台设置。详见readme部分

**Comment by ddiu8081** [comment]
> 这个问题已解决多谢，另外想问下搜索功能配置已开启，为什么我这边按主题并搜不到任何结果呢？

有具体链接地址么？另外，目前的搜索功能只能按标题搜索，而且只有在输入两个字符以上才开启展示

**Comment by hiddletian** [comment]
tech.iyunsu.cn,另外添加背景图片成功，貌似不显示错误是什么情况，完全不了解前端

**Comment by ddiu8081** [comment]
> tech.iyunsu.cn,另外添加背景图片成功，貌似不显示错误是什么情况，完全不了解前端

感觉是ghost安装的时候url配置有问题，建议检查一下

**Comment by hiddletian** [comment]
你指的是config.js文件吧，我发现修改url,重启的时候并没有加载最新的url地址
