### ISSUE TITLE
[Bug]锚点定位有偏移

### ISSUE THREAD

**Issue by tenhow** [ddiu8081/ghost-theme-Moegi#18]
Diu兄，我在脚注跳转过程中发现有个问题，就是锚点定位有偏差，我猜测是TOC的position:fixd引起的，但是我查了下资料，貌似修起来有点复杂，我不是搞前端的，有点看不太懂解决方案。

如: https://www.jianshu.com/p/3a4c40d31e5b

**Comment by tenhow** [comment]
标题的互跳是没有问题的。
目前看就脚注和脚注引用的互相跳转有问题，其他没测出来。
但是你看我的二级脚注，从二级脚注引用跳二级脚注没有问题（就是脚注里面再给一个脚注），但跳回二级脚注引用仍是一样的问题。

具体可跳的二级脚注： https://blog.no.mk/reactivecocoa-his/#fn2-0

**Comment by tenhow** [comment]
要是能劫持了每次的点击，用jquery来跳倒是很准，但是不知道这种方式有没有实现的可能。

**Comment by ddiu8081** [comment]
![image](https://user-images.githubusercontent.com/1998168/51790067-94cc3780-21cb-11e9-82f6-c11511658129.png)

不知道 这段css是什么作用，但是删掉这一节可以解决问题。
`.single-post a:not(.nav-choosed):before`

**Comment by tenhow** [comment]
<ruby>6666啊，精确打击！<rt>你真棒！</rt></ruby>果然解决问题了！很开心
这段话是<ruby>我之前想给一个a标签引入一个动画效果<rt>没想到引入了这个bug</rt><ruby>,就在这里加了一个not，然后想单独定义了那个类的效果。

**Comment by tenhow** [comment]
问题解决了，这个issue,那我关了哈:/）
