### ISSUE TITLE
Ghost2.0以后是否还需要打开API？

### ISSUE THREAD

**Issue by yuxiaoba** [ddiu8081/ghost-theme-Moegi#19]
我按照指导在 Ghost 后台新建独立页面（勾选Turn this post into a page），标题随意（如归档），页面地址为archives，在设置中添加指向该地址的菜单。
然后归档页是空白的。
看网页报错是
```
(index):98 The {{get}} helper is not available. The Public API flag must be enabled in labs if you wish to use the {{get}} helper
```
但是现在的后台已经没有打开这个选项啊？请问应该怎么打开啊

**Comment by ddiu8081** [comment]
从错误信息来看确实是没有开启api。
我目前在用的 Ghost 版本是 `2.8.0`，后台是有开启选项的（Labs下）。
稍后我升级到`2.14`试试。

**Comment by ddiu8081** [comment]
![image](https://user-images.githubusercontent.com/1998168/52910497-41816c80-32d3-11e9-9545-f86d49dccecc.png)
在`2.14`后台应该还保留有开启公共api的选项。

同时，Ghost Public Api 即将被弃用，该主题也将更新新的归档逻辑。

**Comment by yuxiaoba** [comment]
奇怪呀，我的后台竟然没有
![image](https://user-images.githubusercontent.com/35029651/52910604-cb7e0500-32d4-11e9-8819-5bba64d06da0.png)

**Comment by yuxiaoba** [comment]
我的版本是ghost2.14.3，应该跟你的一样呀，是不是后台的版本问题啊？

**Comment by ddiu8081** [comment]
> 我的版本是ghost2.14.3，应该跟你的一样呀，是不是后台的版本问题啊？

在全新安装的站点中，该复选框会被删除，导致无法获取文章列表。

目前还在尝试新的解决方案。

**Comment by betwowt** [comment]
把package.json 中的
```
    "engines": {
        "ghost": ">=1.0.0"
    }
```

更改为

```
    "engines": {
        "ghost": ">=1.0.0",
	"ghost-api": "v2"
    }
```

**Comment by ddiu8081** [comment]
> 把package.json 中的
> 
> ```
>     "engines": {
>         "ghost": ">=1.0.0"
>     }
> ```
> 更改为
> 
> ```
>     "engines": {
>         "ghost": ">=1.0.0",
> 	"ghost-api": "v2"
>     }
> ```

不知道更改之后会不会对旧版 Ghost 有影响？

**Comment by betwowt** [comment]
@ddiu8081 只是针对新版的解决方式

**Comment by ddiu8081** [comment]
> @ddiu8081 只是针对新版的解决方式

ok，了解，感谢。

**Comment by yuxiaoba** [comment]
@betwowt 你这样做可以吗？我改过这个但是并没有用啊，是不是还有其他步骤？

**Comment by betwowt** [comment]
> @betwowt 你这样做可以吗？我改过这个但是并没有用啊，是不是还有其他步骤？

改完之后默认是已经添加了openapi , 后台没有这个选项，但是是可以使用标签云的

**Comment by yuxiaoba** [comment]
那归档页，搜索功能那些呢？

**Comment by yuxiaoba** [comment]
但是像归档页，搜索功能好像都不行是吗？

**Comment by ddiu8081** [comment]
> 但是像归档页，搜索功能好像都不行是吗？

看起来像是需要手动配置一下，还没研究清楚

**Comment by betwowt** [comment]
@yuxiaoba clone一下最新代码,不知道能不能帮到你

**Comment by yuxiaoba** [comment]
OK了哦，谢谢大佬们

**Comment by yuxiaoba** [comment]
不过新的归档页的代码是对每一篇来进行归档的，请问要改成按月或者按年归档要怎么改啊？

**Comment by ddiu8081** [comment]
> 不过新的归档页的代码是对每一篇来进行归档的，请问要改成按月或者按年归档要怎么改啊？

最新的提交应该是解决了，感谢 @yuxiaoba @betwowt @xiaoluoboding
