### ISSUE TITLE
标签云样式展示异常,同一个标签被分隔为两行

### ISSUE THREAD

**Issue by 1314cc** [ddiu8081/ghost-theme-Moegi#23]
![1552705562700](https://user-images.githubusercontent.com/5126487/54470002-adc09480-47db-11e9-9a03-5df5b5748084.jpg)
标签被换行分隔了.

**Comment by ddiu8081** [comment]
![image](https://user-images.githubusercontent.com/1998168/54470140-ebbeb800-47dd-11e9-9747-117fa8fbddb1.png)

已修复。感谢
