### ISSUE TITLE
标签展示数量和统计标签数量对应不上. 

### ISSUE THREAD

**Issue by 1314cc** [ddiu8081/ghost-theme-Moegi#24]
![1552706849408](https://user-images.githubusercontent.com/5126487/54470184-a8b11480-47de-11e9-92dc-ca26b1e53fcf.jpg)
显示8个标签,但是上面统计共9个标签

**Comment by ddiu8081** [comment]
后台确实是添加了9个标签...这个是因为某个标签下没有文章所以列出来8个

**Comment by 1314cc** [comment]
嗯，我也是有几个标签没显示出来。
