### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by mike-code** [ddiu8081/ghost-theme-Moegi#25]
Any chance that you share the `./src` so that I can modify some of the styles/js myself and then compile with gulp?

Thanks!

**Comment by ddiu8081** [comment]
Sorry, but I haven't use gulp or any other build systems yet.
You can only modify styles directly.

I've put it on the list and studying gulp. You may see it future :)

**Comment by mike-code** [comment]
Oh alright. The `gulpfile.js` in the project confused me

**Comment by ddiu8081** [comment]
Sorry for confusing you. 😅
