### ISSUE TITLE
建议作者页面加入头像

### ISSUE THREAD

**Issue by e14883362** [ddiu8081/ghost-theme-Moegi#26]
自己尝试了几次，总是不满意。
这里我发表 datetime 本地化的文章：http://e.ymjt.com.cn/ghost-datetime/

**Comment by e14883362** [comment]
同时修改了不少地方，搜索也修复了。

**Comment by ddiu8081** [comment]
看到了，十分感谢

**Comment by ddiu8081** [comment]
关于头像的问题，这是一个修改好的页面示例，没有问题的话会稍后更新~
https://blog.ddiu.site/author/ddiu8081/

**Comment by e14883362** [comment]
> 关于头像的问题，这是一个修改好的页面示例，没有问题的话会稍后更新~
> https://blog.ddiu.site/author/ddiu8081/

对对，就是这个效果。谢谢！

**Comment by ddiu8081** [comment]
released v1.10.2
