### ISSUE TITLE
请教，如何在ghost的casper主题中添加TOC？

### ISSUE THREAD

**Issue by clairgu** [ddiu8081/ghost-theme-Moegi#7]
您好，
请教，如何在ghost的casper主题中添加TOC？我试了您说的方法，在paritals添加了toc.hbs, 并且在default.hbs引用了jquery.min.js，以及在post.hbs添加了{{> "toc"}},还有screen.css也添加了toc的部分，但是仍然无法显示TOC，请问还有什么地方我没考虑到的吗？

**Comment by ddiu8081** [comment]
@clairgu 
* 有可能是某个库没有引入进来，查看console是否有报错？
* 查看文章页源码，是否有id为toc的div？
* 写文章的时候要有h2、h3这些标题，因为插件只会解析特定的标题。

**Comment by clairgu** [comment]
@ddiu8081 好的，谢谢，我后来解决了，是css的问题
