### ISSUE TITLE
在Github下载zip后，上传到Ghost后台报错

### ISSUE THREAD

**Issue by missy0u** [ddiu8081/ghost-theme-Moegi#8]
Version 2.1.4

![image](https://user-images.githubusercontent.com/3926664/46253009-6f8d1e00-c4a4-11e8-8d5e-3b73f2ee2402.png)

![image](https://user-images.githubusercontent.com/3926664/46253019-8d5a8300-c4a4-11e8-8b1c-758fc76dfb13.png)

**Comment by ddiu8081** [comment]
改了一下，再试试？ @missy0u

**Comment by missy0u** [comment]
nice @ddiu8081
